# Generated by Django 2.0.5 on 2018-10-04 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drafts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drafts',
            name='author',
            field=models.CharField(default='N/A', max_length=20),
            preserve_default=False,
        ),
    ]
