# Generated by Django 2.0.5 on 2018-10-17 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drafts', '0002_drafts_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='drafts',
            name='slug',
            field=models.SlugField(default='becca-dsouza'),
            preserve_default=False,
        ),
    ]
